yijisoo/yijisoo.github.io

ie59000/2015spring/hw2/hw2.json

TAEJIN, KIM - http://taejin0128.github.io/index2.html

I update my URL

---

ie59000/2015spring/hw2/hw2.json

Correct pull request, changing my branch and adding URL

adding nsalas24 URL

---

ie59000/2015spring/hw2/hw2.json

Please include the URL to my webpage with HW 2.
Manuel Ramirez

Add manuelrp07 URL

---

ie59000/2015spring/projects/projects.json

Update team project name and URL

Update team project name and URL

---

ie59000/2015spring/hw2/hw2.json

HW not complete.....testing well in advance of weekend to make sure I understand pull requests.

Jeremy Black

---

ie59000/2015spring/projects/projects.json

added team name for MQM

---

ie59000/2015spring/hw2/hw2.json

Signed-off-by: wenxuan-xia <wenxuan.xia@hotmail.com>

Add Wenxuan Xia's Homework-2 link.

---

ie59000/2015spring/projects/projects.json

Update Team URL

---

ie59000/2015spring/hw2/hw2.json

I found I couldn't correctly open my link in your given front page. This change may help.

add "http" in my url

---

ie59000/2015spring/projects/projects.json

submit team url

---

ie59000/2015spring/projects/projects.json

Added info for Katie Ernst

---

ie59000/2015spring/projects/projects.json

adding group url for VisualBoilers

---

ie59000/2015spring/hw2/hw2.json

Add Te-Wei URL

---

ie59000/2015spring/projects/projects.json

Signed-off-by: wenxuan-xia <wenxuan.xia@hotmail.com>

Add project team URL and NAME

---

ie59000/2015spring/hw2/hw2.json

Updated hw2.json line 19 to include my HW2 url

add kphleger's HW2 url

---

ie59000/2015spring/hw3/hw3.json

Mingran HW3

---

ie59000/2015spring/hw3/hw3.json

Includes visualization, vis analysis and Google Analytics.

Update JSON with URL for HW3 part 1

---

ie59000/2015spring/hw3/hw3.json

Update hw3.json-add wenxuan-xia URL

---

ie59000/2015spring/hw3/hw3.json

This link is connected to the hw3 webpage (HW3-1), and a button on the webpage is for connecting the google analytics report (HW3-2).

Update HW3 URL

---

ie59000/2015spring/hw3/hw3.json

Is this the right json? I have sent a couple pull requests and am still not seeing my URL on the web????

Update for Jeremy Black

---

ie59000/2015spring/hw3/hw3.json

Zixu Zhang HW3 url

---

ie59000/2015spring/hw3/hw3.json

Renner Turn in

---

ie59000/2015spring/hw4/hw4.json

Noah Salas HW4

---

ie59000/2015spring/hw4/hw4.json

Mingran_HW4

---

ie59000/2015spring/hw4/hw4.json

paste my HW4 link

---

ie59000/2015spring/hw4/hw4.json

2nd attempt at submitting pull request.
I was the first one to submit my link for HW4 (8 days ago according to GitHub). I don't know why it wasn't received.

Re-do Pull Request
